//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaMovies.DeltaAPI.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorInMovie
    {
        public long Id { get; set; }
        public int ActorId { get; set; }
        public long MovieId { get; set; }
    
        public virtual ActorInfo ActorInfo { get; set; }
        public virtual MovieInfo MovieInfo { get; set; }
    }
}
