//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaMovies.DeltaAPI.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieInfo
    {
        public MovieInfo()
        {
            this.ActorInMovies = new HashSet<ActorInMovie>();
        }
    
        public long MovieId { get; set; }
        public string Name { get; set; }
        public int YearOfRelease { get; set; }
        public string Plot { get; set; }
        public string Poster { get; set; }
        public int ProducedBy { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ProducerInfo ProducerInfo { get; set; }
        public virtual ICollection<ActorInMovie> ActorInMovies { get; set; }
    }
}
